// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI1X09KJBX6hatU56BTGbehw0M48UKG1E',
    appId: '1:603522094378:web:fe3a7f544a06c1193aba53',
    messagingSenderId: '603522094378',
    projectId: 'study-room-finder-1c011',
    authDomain: 'study-room-finder-1c011.firebaseapp.com',
    databaseURL: 'https://study-room-finder-1c011-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'study-room-finder-1c011.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_I8KvJ2AlCJa8BluSJFlCdcm6pryMmIM',
    appId: '1:603522094378:android:784b806550b40db93aba53',
    messagingSenderId: '603522094378',
    projectId: 'study-room-finder-1c011',
    databaseURL: 'https://study-room-finder-1c011-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'study-room-finder-1c011.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCePz12wT5v9W5mma-i3AsMj9TkVKY2GXQ',
    appId: '1:603522094378:ios:f3048d8b2149c13a3aba53',
    messagingSenderId: '603522094378',
    projectId: 'study-room-finder-1c011',
    databaseURL: 'https://study-room-finder-1c011-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'study-room-finder-1c011.firebasestorage.app',
    iosBundleId: 'com.example.mis.studyRoomFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCePz12wT5v9W5mma-i3AsMj9TkVKY2GXQ',
    appId: '1:603522094378:ios:f3048d8b2149c13a3aba53',
    messagingSenderId: '603522094378',
    projectId: 'study-room-finder-1c011',
    databaseURL: 'https://study-room-finder-1c011-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'study-room-finder-1c011.firebasestorage.app',
    iosBundleId: 'com.example.mis.studyRoomFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI1X09KJBX6hatU56BTGbehw0M48UKG1E',
    appId: '1:603522094378:web:9843e1a24425ad083aba53',
    messagingSenderId: '603522094378',
    projectId: 'study-room-finder-1c011',
    authDomain: 'study-room-finder-1c011.firebaseapp.com',
    databaseURL: 'https://study-room-finder-1c011-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'study-room-finder-1c011.firebasestorage.app',
  );
}
